#!/usr/bin/env ruby
require 'erb'
require 'yaml'
require 'ostruct'

unless ARGV[0]
  puts "Usage : #{$0} <YAML_FILE> [test]"
  puts "\t[test] is optional, if set output will be the YAML configuration"
  exit
end

yaml = YAML.load_file( ARGV[0] )

templates_path = ''
if File.exists?( '.gen_config.conf' )
	templates_path = YAML.load_file( '.gen_config.conf' )['template_path']
elsif File.exists?( "#{ENV['HOME']}/.gen_config.conf" )
	templates_path = YAML.load_file( "#{ENV['HOME']}/.gen_config.conf" )['template_path']
elsif File.exists?( "/etc/gen_config.conf" )
	templates_path = YAML.load_file( '/etc/gen_config.conf' )['template_path']
else
	templates_path = "#{ENV['PWD']}/templates"
end

yaml.each do |var|
  template = ERB.new( File.read( "#{templates_path}/#{var['template']}" ) )
  c = OpenStruct.new( var )

  puts template.result( c.send( :binding ) )	
end
