#!/usr/bin/env ruby
require 'erb'
require 'yaml'
require 'ostruct'

unless ARGV[0]
  puts "Usage : #{$0} <YAML_FILE> [test]"
  puts "\t[test] is optional, if set output will be the YAML configuration"
  exit
end

yaml = YAML.load( File.read( ARGV[0] ) )

if ARGV[1] == "test"
  puts YAML::dump( yaml )
  exit
end

yaml.each do |config|
  @template = ERB.new( File.read( "templates/#{config['template']}" ) )
  c= OpenStruct.new( config )
  
  puts @template.result( c.send( :binding ) )
end
